#ifndef BASIC_BOARDGAMES_UNIVERSAL_DEFINITIONS_H
#define BASIC_BOARDGAMES_UNIVERSAL_DEFINITIONS_H

#endif //BASIC_BOARDGAMES_UNIVERSAL_DEFINITIONS_H

#define MAX_PLAYERS 2

#define STATUS {CONTINUE,OVER};
#define enum gameStatus

int number_of_games();